FROM python:3
WORKDIR /usr/src/app
COPY service_python ./
ADD odbcinst.ini /etc/odbcinst.ini
RUN apt-get update
RUN apt-get install -y gcc tdsodbc unixodbc-dev
RUN apt install unixodbc-bin -y
RUN apt-get clean -y
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-u", "init.py", "prod"]