FROM python:3.6
ENV PYTHONUNBUFFERED 1
WORKDIR /usr/src/app
COPY service_python ./
RUN apt-get update && apt-get install -y \
	openjdk-8-jre
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
RUN export JAVA_HOME
RUN pip install -U pip
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-u", "init.py", "prod"]
