FROM python:3.6
ENV PYTHONUNBUFFERED 1
WORKDIR /usr/src/app
COPY service_python ./
RUN apt-get update 
RUN apt-get install -y python3.7-dev
RUN apt-get install -y openjdk-11-jre
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
RUN export JAVA_HOME
RUN pip install -U pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip3 install --no-cache-dir JPype1==0.6.3 --force-reinstall
CMD ["python", "-u", "init.py", "prod"]
