version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile-frontend"
    ports:
      - "8090:8090"
    environment:
      - TZ=America/Mexico_City
  service:
    build:
      context: .
      dockerfile: "Dockerfile-service"
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Mexico_City
