version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile-frontend"
    ports:
      - "8090:80"
    environment:
      - TZ=America/Mexico_City
    networks:
      - netmonitoring
  service:
    build:
      context: .
      dockerfile: "Dockerfile-service"
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Mexico_City
    networks:
      netmonitoring:
          aliases:
          - backservice
networks:
   netmonitoring:
